In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("nba_games.csv",index_col=0)

In [4]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [5]:
df = df.sort_values("date")

In [6]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
16086,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
16904,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
16905,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
16087,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
1225,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,240.0,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
11533,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
11532,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
7477,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
7476,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [7]:
df = df.reset_index(drop=True)

In [8]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [9]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [10]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team" , group_keys=False).apply(add_target)

In [11]:
df[df["team"] == "GSW"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,True
44,240.0,43.0,93.0,0.462,9.0,26.0,0.346,17.0,25.0,0.680,...,37.5,151.0,118.0,HOU,92,1,2016,2015-10-30,True,True
67,240.0,46.0,84.0,0.548,17.0,30.0,0.567,25.0,35.0,0.714,...,36.1,218.0,131.0,NOP,120,1,2016,2015-10-31,True,True
98,240.0,43.0,84.0,0.512,11.0,25.0,0.440,22.0,30.0,0.733,...,44.3,106.0,126.0,MEM,69,0,2016,2015-11-02,True,True
137,240.0,39.0,85.0,0.459,10.0,26.0,0.385,24.0,31.0,0.774,...,32.9,250.0,122.0,LAC,108,0,2016,2015-11-04,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17762,240.0,39.0,86.0,0.453,15.0,37.0,0.405,14.0,20.0,0.700,...,35.2,300.0,117.0,BOS,88,0,2022,2022-06-05,True,False
17764,240.0,36.0,78.0,0.462,15.0,40.0,0.375,13.0,15.0,0.867,...,28.8,175.0,117.0,BOS,116,1,2022,2022-06-08,False,True
17766,240.0,40.0,91.0,0.440,15.0,43.0,0.349,12.0,15.0,0.800,...,32.4,205.0,120.0,BOS,97,1,2022,2022-06-10,True,True
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,True
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,NaN

In [12]:
df["team"]

0        NOP
1        CLE
2        CHI
3        GSW
4        ATL
        ...
17767    BOS
17768    GSW
17769    BOS
17770    BOS
17771    GSW
Name: team, Length: 17772, dtype: object

In [14]:
df["target"][pd.isnull(df["target"])] = 2

/var/folders/33/zy_63xr15s1bdpd0cwr1d1sc0000gn/T/ipykernel_11245/1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [15]:
df["target"] = df["target"].astype(int, errors="ignore")

In [16]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [17]:
df["won"].value_counts()

False    8886
True     8886
Name: won, dtype: int64

In [18]:
df["target"].value_counts()

1    8872
0    8870
2      30
Name: target, dtype: int64

In [19]:
nulls = pd.isnull(df)

In [20]:
nulls

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17768,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17769,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17770,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17771,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [21]:
nulls = nulls.sum()

In [23]:
nulls = nulls[nulls>0]

In [24]:
nulls

+/-             17772
mp_max          17772
mp_max.1        17772
+/-_opp         17772
mp_max_opp      17772
mp_max_opp.1    17772
dtype: int64

In [25]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [26]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [27]:
df = df[valid_columns].copy()

In [28]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [51]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/justin/anaconda3/lib/python3.11/site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in /Users/justin/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in /Users/justin/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /Users/justin/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/justin/anaconda3/lib/python3.11/site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [52]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [114]:
removed_columns = ["season","date","won","target","team", "team_opp", "team_y", "team_x", "team_opp_next_y", "team_opp_next_x", "date_next", "date"]

In [115]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [55]:
from sklearn.preprocessing import MinMaxScaler

scaler= MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [56]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.317647,GSW,0.451923,1.0,2016,2015-10-27,False,0
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.317647,CHI,0.317308,1.0,2016,2015-10-27,False,1
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.329412,CLE,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.505882,NOP,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.317647,DET,0.403846,0.0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.182285,0.208531,0.411765,GSW,0.413462,0.0,2022,2022-06-10,False,0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.411765,BOS,0.288462,0.0,2022,2022-06-13,True,1
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.352941,GSW,0.384615,1.0,2022,2022-06-13,False,0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.400000,GSW,0.375000,0.0,2022,2022-06-16,False,2
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.576471,BOS,0.250000,1.0,2022,2022-06-16,True,2

In [60]:
sfs.fit(df[selected_columns].head(100), df["target"].head(100))

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [62]:
predictors = list(selected_columns[sfs.get_support()])

In [63]:
predictors

['mp',
 'fg%',
 '3p%',
 'orb',
 'ts%',
 'usg%',
 '3p%_max',
 'ft_max',
 'fta_max',
 '+/-_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'usg%_max',
 'mp_opp',
 'fg_opp',
 '3p_opp',
 'ft%_opp',
 'blk_opp',
 'usg%_opp',
 'fga_max_opp',
 '3p_max_opp',
 'ft_max_opp',
 'ft%_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 'drb%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp']

In [66]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual","prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [67]:
predictions = backtest(df, rr, predictors)

In [68]:
predictions

       actual  prediction
5250        1           1
5251        1           1
5252        0           0
5253        1           0
5254        0           1
...       ...         ...
17767       0           0
17768       1           1
17769       0           1
17770       2           1
17771       2           1

[12522 rows x 2 columns]

In [70]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] !=2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5485110470701249

In [71]:
df.groupby("home").apply(lambda x: x[x["won"] ==1].shape[0] / x.shape[0])

home
0.0    0.428314
1.0    0.571686
dtype: float64

In [72]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.317647,GSW,0.451923,1.0,2016,2015-10-27,False,0
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.317647,CHI,0.317308,1.0,2016,2015-10-27,False,1
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.329412,CLE,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.505882,NOP,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.317647,DET,0.403846,0.0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.182285,0.208531,0.411765,GSW,0.413462,0.0,2022,2022-06-10,False,0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.411765,BOS,0.288462,0.0,2022,2022-06-13,True,1
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.352941,GSW,0.384615,1.0,2022,2022-06-13,False,0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.400000,GSW,0.375000,0.0,2022,2022-06-16,False,2
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.576471,BOS,0.250000,1.0,2022,2022-06-16,True,2

In [83]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [84]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.079,0.679245,0.277279,0.554502,0.317647,0.451923,1.0,False,NOP,2016
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.140,0.509434,0.160462,0.345972,0.317647,0.317308,1.0,False,CLE,2016
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.185,0.270440,0.088575,0.232227,0.329412,0.298077,0.0,True,CHI,2016
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.063,0.344864,0.215661,0.530806,0.505882,0.298077,0.0,True,GSW,2016
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.047,0.300839,0.019255,0.203791,0.317647,0.403846,0.0,False,ATL,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.103,0.401468,0.182285,0.208531,0.411765,0.413462,0.0,False,BOS,2022
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.124,0.423480,0.928113,1.000000,0.411765,0.288462,0.0,True,GSW,2022
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.076,0.300839,0.181001,0.630332,0.352941,0.384615,1.0,False,BOS,2022
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.063,0.300839,0.120668,0.459716,0.400000,0.375000,0.0,False,BOS,2022
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.160,1.000000,0.263158,0.246445,0.576471,0.250000,1.0,True,GSW,2022

In [85]:
def find_team_averages(team):
    rolling = team.rolling(8).mean()
    return rolling

df_rolling = df_rolling.groupby(["team","season"], group_keys=False).apply(find_team_averages)

/var/folders/33/zy_63xr15s1bdpd0cwr1d1sc0000gn/T/ipykernel_11245/3418624385.py:2: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['team'], dtype='object')
  rolling = team.rolling(8).mean()

In [86]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,season
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.366477,0.303309,0.397727,0.448276,0.475379,0.430226,0.421512,0.365079,0.751896,...,0.054500,0.121500,0.528826,0.177471,0.438981,0.497059,0.335337,0.500,0.625,2022.0
17768,0.0,0.474432,0.375000,0.472488,0.465517,0.509470,0.425475,0.319767,0.275794,0.781359,...,0.068500,0.117250,0.383648,0.324615,0.719194,0.550000,0.399038,0.500,0.625,2022.0
17769,0.0,0.366477,0.297794,0.402512,0.461207,0.471591,0.446407,0.389535,0.351190,0.727830,...,0.055875,0.118250,0.528826,0.185494,0.499408,0.472059,0.361779,0.625,0.500,2022.0
17770,0.0,0.369318,0.314338,0.390550,0.465517,0.462121,0.459768,0.372093,0.329365,0.753792,...,0.056875,0.122000,0.441431,0.182606,0.491114,0.470588,0.389423,0.500,0.375,2022.0
17771,0.0,0.474432,0.395221,0.455742,0.500000,0.535985,0.435719,0.279070,0.242063,0.798862,...,0.067875,0.131125,0.492794,0.327182,0.700829,0.536765,0.387019,0.500,0.625,2022.0

In [87]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df,df_rolling], axis=1)

In [88]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.054500,0.121500,0.528826,0.177471,0.438981,0.497059,0.335337,0.500,0.625,2022.0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.068500,0.117250,0.383648,0.324615,0.719194,0.550000,0.399038,0.500,0.625,2022.0
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.055875,0.118250,0.528826,0.185494,0.499408,0.472059,0.361779,0.625,0.500,2022.0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.056875,0.122000,0.441431,0.182606,0.491114,0.470588,0.389423,0.500,0.375,2022.0
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.067875,0.131125,0.492794,0.327182,0.700829,0.536765,0.387019,0.500,0.625,2022.0

In [89]:
df = df.dropna()

In [90]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
175,0.0,0.545455,0.470588,0.473684,0.448276,0.439394,0.467933,0.325581,0.222222,1.000000,...,0.060500,0.074625,0.404219,0.119544,0.387441,0.451471,0.329327,0.500,0.875,2016.0
197,0.0,0.340909,0.352941,0.325359,0.241379,0.227273,0.437055,0.279070,0.285714,0.631272,...,0.065250,0.112875,0.464885,0.145539,0.434242,0.401471,0.448317,0.250,0.125,2016.0
198,0.0,0.272727,0.264706,0.306220,0.344828,0.439394,0.359857,0.255814,0.253968,0.656943,...,0.071625,0.066500,0.295466,0.143453,0.377962,0.386765,0.361779,0.625,0.375,2016.0
199,0.0,0.340909,0.250000,0.413876,0.379310,0.318182,0.522565,0.395349,0.333333,0.787631,...,0.063500,0.087875,0.546777,0.148909,0.280213,0.369118,0.306490,0.375,0.500,2016.0
200,0.0,0.568182,0.382353,0.581340,0.448276,0.409091,0.497625,0.116279,0.095238,0.833139,...,0.069375,0.079000,0.426101,0.135751,0.406398,0.467647,0.342548,0.500,0.875,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.054500,0.121500,0.528826,0.177471,0.438981,0.497059,0.335337,0.500,0.625,2022.0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.068500,0.117250,0.383648,0.324615,0.719194,0.550000,0.399038,0.500,0.625,2022.0
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.055875,0.118250,0.528826,0.185494,0.499408,0.472059,0.361779,0.625,0.500,2022.0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.056875,0.122000,0.441431,0.182606,0.491114,0.470588,0.389423,0.500,0.375,2022.0
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.067875,0.131125,0.492794,0.327182,0.700829,0.536765,0.387019,0.500,0.625,2022.0

In [92]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df,"home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

/var/folders/33/zy_63xr15s1bdpd0cwr1d1sc0000gn/T/ipykernel_11245/1523111835.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df,"home")
/var/folders/33/zy_63xr15s1bdpd0cwr1d1sc0000gn/T/ipykernel_11245/1523111835.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
/var/folders/33/zy_63xr15s1bdpd0cwr1d1sc0000gn/T/ipykernel_11245/1523111835.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [93]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10,home_next,team_opp_next,date_next
175,0.0,0.545455,0.470588,0.473684,0.448276,0.439394,0.467933,0.325581,0.222222,1.000000,...,0.119544,0.387441,0.451471,0.329327,0.500,0.875,2016.0,1.0,MIN,2015-11-09
197,0.0,0.340909,0.352941,0.325359,0.241379,0.227273,0.437055,0.279070,0.285714,0.631272,...,0.145539,0.434242,0.401471,0.448317,0.250,0.125,2016.0,1.0,DET,2015-11-11
198,0.0,0.272727,0.264706,0.306220,0.344828,0.439394,0.359857,0.255814,0.253968,0.656943,...,0.143453,0.377962,0.386765,0.361779,0.625,0.375,2016.0,1.0,LAL,2015-11-11
199,0.0,0.340909,0.250000,0.413876,0.379310,0.318182,0.522565,0.395349,0.333333,0.787631,...,0.148909,0.280213,0.369118,0.306490,0.375,0.500,2016.0,0.0,BOS,2015-11-11
200,0.0,0.568182,0.382353,0.581340,0.448276,0.409091,0.497625,0.116279,0.095238,0.833139,...,0.135751,0.406398,0.467647,0.342548,0.500,0.875,2016.0,1.0,NOP,2015-11-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.177471,0.438981,0.497059,0.335337,0.500,0.625,2022.0,0.0,GSW,2022-06-13
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.324615,0.719194,0.550000,0.399038,0.500,0.625,2022.0,0.0,BOS,2022-06-16
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.185494,0.499408,0.472059,0.361779,0.625,0.500,2022.0,1.0,GSW,2022-06-16
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.182606,0.491114,0.470588,0.389423,0.500,0.375,2022.0,NaN,None,None
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.327182,0.700829,0.536765,0.387019,0.500,0.625,2022.0,NaN,None,None

In [95]:
df = df.copy()

In [97]:
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]],
    left_on = ["team", "date_next"],
    right_on = ["team_opp_next", "date_next"]
)

In [98]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,season_10_y,team_opp_next_y,team_y
0,0.0,0.500000,0.529412,0.377990,0.344828,0.318182,0.475059,0.418605,0.349206,0.796966,...,0.443527,0.143293,0.383886,0.435294,0.341346,0.625,0.500,2016.0,CHI,CHO
1,0.0,0.363636,0.294118,0.404306,0.068966,0.106061,0.216152,0.441860,0.444444,0.638273,...,0.402385,0.237003,0.392773,0.527941,0.318510,0.375,1.000,2016.0,MEM,GSW
2,0.0,0.545455,0.455882,0.488038,0.413793,0.257576,0.678147,0.232558,0.190476,0.820303,...,0.428328,0.098363,0.495853,0.345588,0.353365,0.750,0.375,2016.0,GSW,MEM
3,0.0,0.409091,0.205882,0.552632,0.379310,0.303030,0.543943,0.744186,0.666667,0.728121,...,0.386792,0.129814,0.342417,0.414706,0.358173,0.500,0.375,2016.0,CLE,NYK
4,0.0,0.568182,0.382353,0.581340,0.517241,0.287879,0.774347,0.488372,0.444444,0.718786,...,0.384041,0.176348,0.431872,0.354412,0.408654,0.375,0.000,2016.0,OKC,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16197,0.0,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.386923,0.269416,0.609597,0.591176,0.414663,0.375,0.625,2022.0,BOS,GSW
16198,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.528826,0.177471,0.438981,0.497059,0.335337,0.500,0.625,2022.0,GSW,BOS
16199,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.377096,0.236842,0.630332,0.586765,0.426683,0.500,0.625,2022.0,BOS,GSW
16200,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.528826,0.185494,0.499408,0.472059,0.361779,0.625,0.500,2022.0,GSW,BOS
16201,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.383648,0.324615,0.719194,0.550000,0.399038,0.500,0.625,2022.0,BOS,GSW

In [99]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        CHI             CHO    CHO             CHI  2015-11-13
1        MEM             GSW    GSW             MEM  2015-11-11
2        GSW             MEM    MEM             GSW  2015-11-11
3        CLE             NYK    NYK             CLE  2015-11-13
4        OKC             PHI    PHI             OKC  2015-11-13
...      ...             ...    ...             ...         ...
16197    BOS             GSW    GSW             BOS  2022-06-10
16198    GSW             BOS    BOS             GSW  2022-06-13
16199    BOS             GSW    GSW             BOS  2022-06-13
16200    GSW             BOS    BOS             GSW  2022-06-16
16201    BOS             GSW    GSW             BOS  2022-06-16

[16202 rows x 5 columns]

In [116]:
remove_columns = list(full.columns[full.dtypes =="object"]) + removed_columns

In [117]:
removed_columns

['season',
 'date',
 'won',
 'target',
 'team',
 'team_opp',
 'team_y',
 'team_x',
 'team_opp_next_y',
 'team_opp_next_x',
 'date_next',
 'date']

In [118]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [122]:
sfs.fit(full[selected_columns].head(30), full["target"].head(30))

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [124]:
predictors = list(selected_columns[sfs.get_support()])

In [125]:
predictors

['mp',
 'fg',
 'fga',
 'fg%',
 '3p',
 '3pa',
 '3p%',
 'ft',
 'fta',
 'ft%',
 'orb',
 'drb',
 'trb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'ts%',
 'efg%',
 '3par',
 'ftr',
 'orb%',
 'drb%',
 'trb%',
 'ast%',
 'ast%_max',
 'won_10_x',
 'home_next']

In [126]:
predictions = backtest(full, rr, predictors)

In [127]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.5878277646233447